### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by cxp-13** [solana-developers/helpers#57]
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/cxp/solana_learn/solana-lab-token22-metadata/node_modules/@solana-developers/helpers/dist/esm/lib/keypair.js.js' imported from /home/cxp/solana_learn/solana-lab-token22-metadata/node_modules/@solana-developers/helpers/dist/esm/index.js
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:980:10)
    at defaultResolve (node:internal/modules/esm/resolve:1206:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36) {
  url: 'file:///home/cxp/solana_learn/solana-lab-token22-metadata/node_modules/@solana-developers/helpers/dist/esm/lib/keypair.js.js',
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by cxp-13** [comment]
reduce version to 2.3.0

**Comment by liompei** [comment]
I encountered the same issue in version 2.5.5

node:internal/modules/run_main:123
    triggerUncaughtException(
    ^
Error: Cannot find module '/nft/nft-client/node_modules/@solana-developers/helpers/dist/esm/lib/keypair.js.js' imported from /Users/xxx/project/anza/nft/nft-client/node_modules/@solana-developers/helpers/dist/esm/index.js
    at finalizeResolution (/Users/xxx/project/anza/nft/nft-client/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:352:11)
    at moduleResolve (/Users/xxx/project/anza/nft/nft-client/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/Users/xxx/project/anza/nft/nft-client/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /Users/xxx/project/anza/nft/nft-client/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/Users/xxx/project/anza/nft/nft-client/node_modules/ts-node/src/esm.ts:168:34)
    at /Users/xxx/project/anza/nft/nft-client/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/Users/xxx/project/anza/nft/nft-client/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/Users/xxx/project/anza/nft/nft-client/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)

Node.js v22.8.0

**Comment by heyAyushh** [comment]
same as #55 

Thanks for reporting.
