### ISSUE TITLE
createAccountsMintsAndTokenAccounts method doesn't work

### ISSUE THREAD

**Issue by serjou1** [solana-developers/helpers#62]
Here is my code:

```
const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const user = (provider.wallet as anchor.Wallet).payer;
  const payer = user;

  console.log("Payer: ", payer.publicKey.toBase58());

  const connection = provider.connection;

  const accounts = {
    tokenProgram: TOKEN_PROGRAM,
    usdtMint: Keypair.generate().publicKey,
  };

  let owner: anchor.web3.Keypair;
  let regularUser: anchor.web3.Keypair;
  let usdtMint: anchor.web3.Keypair;

  [owner, regularUser, usdtMint] = makeKeypairs(3);

  beforeAll(
    async () => {
      const userMintsAndTokenAccounts =
        await createAccountsMintsAndTokenAccounts(
          [
            [0],
            [1_000_000_000]
          ],
          1 * LAMPORTS_PER_SOL,
          connection,
          payer
        );

      const { users, mints } = userMintsAndTokenAccounts;

      owner = users[0];
      regularUser = users[1];

      usdtMint = mints[0];

      accounts.usdtMint = usdtMint.publicKey;
    }
  );
  
  ```
  
  Here is my log:
  
  ```  
  console.log
    Payer:  zYQ4w3n2evWNHZir1CuYyxR7Kraw7Ec78JverL4Nu55
```

And I'm getting this error:

```
Cannot sign with non signer key FrxYm1E1KYUZHxKWXVnDeu6V1GUTJfo3riAtL1Aj3EFy

      at assert (node_modules/@solana/web3.js/src/utils/assert.ts:6:11)
      at VersionedTransaction.assert [as sign] (node_modules/@solana/web3.js/src/transaction/versioned.ts:104:7)
      at makeAndSendAndConfirmTransaction (node_modules/@solana-developers/helpers/src/lib/token.ts:262:15)
      at createAccountsMintsAndTokenAccounts (node_modules/@solana-developers/helpers/src/lib/token.ts:93:3)
```

My env:

```
serjou@Sergejs-MacBook-Pro anchor % anchor --version
anchor-cli 0.30.1
serjou@Sergejs-MacBook-Pro anchor % solana --version
solana-cli 2.0.15 (src:7feb24da; feat:4052914393, client:Agave)
```

**Comment by serjou1** [comment]
The method only works with 2 mints and 2 users, moreover, no one of users can have 0 both token balances.

I had to change code to:

```
const userMintsAndTokenAccounts =
        await createAccountsMintsAndTokenAccounts(
          [
            [0, 1],
            [1_000_000_000, 0]
          ],
          1 * LAMPORTS_PER_SOL,
          connection,
          payer
        );
```

This should be documented or method should be rewritten

**Comment by mikemaccana** [comment]
@serjou1 yep, when you add more users or tokens you'll hit transaction size limits - make a PR to split this into multiple transactions and it will fix this.

**Comment by kaxxa123** [comment]
Came here after running into the same problem. 

@mikemaccana the function doesn't even work if you try to create one mint for 2 users (see original code of @serjou1) so the issue isn't about transaction limit. The function is probably coded for a single scenario.
